"""Constants for the Bali Művek Home Controller integration."""

DOMAIN = "bmh"

CONF_1W_PORT = "port"
CONF_ADDRESS = "address"
CONF_ADDRESS2 = "address2"
CONF_DEVICE_CLASS = "device_class"
CONF_INVERT = "invert"
CONF_INVERT2 = "invert2"
CONF_IO_INPUT = "input"
CONF_IO_OUTPUT = "output"
CONF_IO_OUTPUT2 = "output2"
CONF_PWM = "pwm"
CONF_TIMEOUT = "timeout"
CONF_TIMEOUT2 = "timeout2"
CONF_TWO_WAY_OUTPUT_TYPE = "output_type"
